### ISSUE TITLE
hi how are you i can't seem to compile the project im a noob

### ISSUE THREAD

**Issue by silentonecodes** [ObsidianLabs/SubstrateIDE#1]
it says error subatrate-ide@0.1.1: The engine "node" is incompatible with this module. Expected version "12". Got "10.19.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by leonlianght** [comment]
It is because you are using a incompatible Node.js version. You may install the Node 12 to solve this issue.
